# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{matching}
  s.version = "0.12.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Barry Ezell}]
  s.date = %q{2012-02-08}
  s.description = %q{}
  s.email = %q{barrye@gmail.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/matching.rb",
    "lib/matching/active_relation_store.rb",
    "lib/matching/array_store.rb",
    "lib/matching/attribute_pair.rb",
    "lib/matching/deduplicator.rb",
    "lib/matching/hash_index.rb",
    "lib/matching/match.rb",
    "lib/matching/matcher.rb",
    "lib/matching/redis_index.rb",
    "lib/matching/similarity.rb",
    "matching.gemspec",
    "spec/db/database.yml",
    "spec/lib/ar_spec.rb",
    "spec/lib/deduplicator_spec.rb",
    "spec/lib/matcher_spec.rb",
    "spec/lib/redis_spec.rb",
    "spec/lib/similarity_spec.rb",
    "spec/samples/agent_recs.csv",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/btedev/matching}
  s.licenses = [%q{MIT license}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.7}
  s.summary = %q{Dataset matching engine}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<text>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<text>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<text>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

